"""
Asynchronous Execution Engine
=============================
Decoupled microstructure execution engine that reads pending orders from CSV
and aggressively monitors the live Level-2 WebSocket stream to execute trades
only when price crosses the entry threshold AND the real-time Order Flow Imbalance (OFI) is favorable.
"""

import sys
import os
import time
import logging
import argparse
import pandas as pd
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from data.fyers_client import FyersBroker
from deployment.config import get_config

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(name)s] %(levelname)s: %(message)s')
logger = logging.getLogger("ExecutionEngine")


class ExecutionEngine:
    def __init__(self, pending_orders_csv: str, broker: FyersBroker):
        self.pending_orders_csv = pending_orders_csv
        self.broker = broker
        self.pending_orders = []
        self.executed_orders = set()
        
    def load_pending_orders(self):
        """Loads pending TradeCalls generated by the ML pipeline."""
        if not os.path.exists(self.pending_orders_csv):
            logger.warning(f"No pending orders found at {self.pending_orders_csv}")
            return []
            
        df = pd.read_csv(self.pending_orders_csv)
        self.pending_orders = df.to_dict('records')
        logger.info(f"Loaded {len(self.pending_orders)} pending orders.")
        return self.pending_orders
        
    def run(self):
        """Main asynchronous event loop for execution."""
        logger.info("Starting Asynchronous Execution Engine...")
        
        # Load pending signals
        self.load_pending_orders()
        if not self.pending_orders:
            logger.info("Engine going to sleep. No pending orders to execute.")
            return
            
        # Extract unique symbols to subscribe to
        symbols = list(set([order['symbol'] for order in self.pending_orders]))
        
        # Start background WebSocket stream
        self.broker.connect_websocket(symbols)
        
        # Wait a few seconds for WS cache to populate
        logger.info("Warming up L2 cache...")
        time.sleep(3)
        
        logger.info(f"Engine is armed and monitoring {len(symbols)} symbols live.")
        
        try:
            while True:
                # Iterate over active pending orders
                for order in self.pending_orders:
                    symbol = order['symbol']
                    direction = order['direction']
                    entry_price = float(order['entry_price'])
                    
                    # Skip if already executed
                    if f"{symbol}_{direction}" in self.executed_orders:
                        continue
                        
                    # Check WS cache for live LTP
                    cache = self.broker.l2_cache.get(symbol, {})
                    live_ltp = cache.get('ltp', 0.0)
                    
                    if live_ltp == 0.0:
                        continue
                        
                    triggered = False
                    
                    # Logic: We assume the ML generator computes entry_price near current price.
                    # For a BUY, if live LTP crosses entry_price (or drops to it), we trigger.
                    # Simple threshold crossing logic:
                    if direction == 'BUY' and live_ltp <= entry_price:
                        triggered = True
                    elif direction == 'SELL' and live_ltp >= entry_price:
                        triggered = True
                        
                    if triggered:
                        logger.info(f"\n[TRIGGER] {symbol} hit Entry Level (LTP: {live_ltp}, Entry: {entry_price})")
                        
                        # --- Microstructure Veto evaluated strictly at point of execution ---
                        live_ofi = self.broker.get_ofi(symbol)
                        logger.info(f"  [{symbol}] Live Microsecond OFI: {live_ofi:.2f}")
                        
                        veto = False
                        if direction == 'BUY' and live_ofi < -0.3:
                            logger.warning(f"  [{symbol}] EXECUTION VETO: Massive Iceberg Sellers detected on the bid! Cancelling BUY.")
                            veto = True
                        elif direction == 'SELL' and live_ofi > 0.3:
                            logger.warning(f"  [{symbol}] EXECUTION VETO: Massive Iceberg Buyers detected on the ask! Cancelling SELL.")
                            veto = True
                            
                        if not veto:
                            logger.info(f"  [{symbol}] ✅ OFI Cleared. Executing Market {direction} Order.")
                            # Example allocation logic (e.g., standard sizing, or could use order['risk_reward'] Kelly fraction)
                            qty = 100 # Example fixed qty, should be computed based on account equity
                            order_id = self.broker.place_order(
                                symbol=symbol,
                                quantity=qty,
                                side=direction,
                                order_type="MARKET",
                                price=0.0
                            )
                            if order_id:
                                logger.info(f"  [{symbol}] 🎯 Order Filled: {order_id}")
                                # TODO: Place bracket orders for Stop Loss & Target 1 here
                        
                        # Mark as executed so we don't spam the broker
                        self.executed_orders.add(f"{symbol}_{direction}")
                        
                # Sleep to prevent 100% CPU usage in the while loop
                # The tick processing could be fully event-driven, but a fast poll loop suffices for now
                time.sleep(0.05)
                
        except KeyboardInterrupt:
            logger.info("Execution Engine Shutting Down.")


def main():
    parser = argparse.ArgumentParser(description="Live Asynchronous Execution Engine")
    parser.add_argument("--orders", type=str, default="data/pending_orders.csv", help="Path to pending orders CSV")
    args = parser.parse_args()
    
    config = get_config()
    client_id = os.environ.get("FYERS_CLIENT_ID")
    secret_key = os.environ.get("FYERS_SECRET_KEY", "")
    
    if not client_id:
        logger.error("FYERS_CLIENT_ID missing in environment. Cannot start Execution Engine.")
        sys.exit(1)
        
    broker = FyersBroker(client_id=client_id, secret_key=secret_key)
    
    engine = ExecutionEngine(
        pending_orders_csv=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), args.orders),
        broker=broker
    )
    
    engine.run()

if __name__ == "__main__":
    main()
